"""add table

Revision ID: d60c13c99acb
Revises: 
Create Date: 2023-12-23 07:31:24.335109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60c13c99acb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=230), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    op.create_table('product_brands',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=225), nullable=False),
    sa.Column('brand_address', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_brands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_brands_updated_at'), ['updated_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=230), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('product_catalogs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=225), nullable=False),
    sa.Column('type', sa.String(length=225), nullable=False),
    sa.Column('image', sa.String(length=225), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('sold_item', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['product_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_catalogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_catalogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_catalogs_updated_at'), ['updated_at'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('todo', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_updated_at'))
        batch_op.drop_index(batch_op.f('ix_todos_created_at'))

    op.drop_table('todos')
    with op.batch_alter_table('product_catalogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_catalogs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_product_catalogs_created_at'))

    op.drop_table('product_catalogs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('product_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_brands_updated_at'))
        batch_op.drop_index(batch_op.f('ix_product_brands_created_at'))

    op.drop_table('product_brands')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
